### PR TITLE
Added changes (demanded)

### PR DESCRIPTION
**Pull request by Lakhankumawat**
Added all the changes which were demanded .....

### CODE REVIEW

**Review by techwithtim — CHANGES_REQUESTED** [review]
Didn't mean to sound demanding, sorry! Could you please fix the indentation to be one tab, not two. Once that is fixed I will be happy to approve :)

**Comment by Lakhankumawat** [comment]
Sure 👍

**Comment by Lakhankumawat** [comment]
> Sure 👍

Actually my mistake i simply copy pasted raw code didn't check indentation : |

**Comment by techwithtim** [comment]
Indentation still messed up... I will do it myself

**Comment by Lakhankumawat** [comment]
> Indentation still messed up... I will do it myself

As you wish 👍

**Pull request closed without merging**
